[tool.uv]
# Default resolver settings
resolver = "strict"
python-version = ">=3.10"

# PyTorch settings by platform
[tool.uv.platform.windows]
extra-index-url = ["https://download.pytorch.org/whl/cu118"]

[tool.uv.platform.darwin]
requirements-file = "requirements_macos.txt"

[tool.uv.platform.linux]
requirements-file = "requirements_linux.txt"
